---
kind: ConfigMap
apiVersion: v1
metadata:
  namespace: rocketmq
  name: configmap-rocketmq-broker-slave-prod
data:
  NAME_SRV_ADDR: "statefulset-rocketmq-namesrv-prod-0.service-rocketmq-namesrv-prod.rocketmq:9876;statefulset-rocketmq-namesrv-prod-1.service-rocketmq-namesrv-prod.rocketmq:9876"
  BROKER_ID: "1"
  BROKER_ROLE: "SLAVE"
  STATEFULSET_NAME: "statefulset-rocketmq-broker-slave-prod"
---
kind: Service
apiVersion: v1
metadata:
  namespace: rocketmq
  name: service-rocketmq-broker-slave-prod
  labels:
    app: service-rocketmq-broker-slave-prod
spec:
  ports:
  - name: rocketmq-port-10909
    protocol: TCP
    port: 10909
    targetPort: 10909
  - name: rocketmq-port-10911
    protocol: TCP
    port: 10911
    targetPort: 10911
  selector:
    app: pod-rocketmq-broker-slave-prod
  type: ClusterIP
  clusterIP: None
  sessionAffinity: ClientIP

---
kind: StatefulSet
apiVersion: apps/v1beta2
metadata:
  namespace: rocketmq
  name: statefulset-rocketmq-broker-slave-prod
  labels:
    app: statefulset-rocketmq-broker-slave-prod
spec:
  replicas: 2
  serviceName: service-rocketmq-broker-slave-prod
  selector:
    matchLabels:
      app: pod-rocketmq-broker-slave-prod
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pod-rocketmq-broker-slave-prod
    spec:
      nodeSelector:
        node: "rocketmq"

      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/szss/rocketmq-broker:v4.3.1
        securityContext:
          privileged: true
        imagePullPolicy: Always
        name: container-rocketmq-broker-slave-prod
        ports:
        - protocol: TCP
          containerPort: 10909
        - protocol: TCP
          containerPort: 10911

        envFrom:
        - configMapRef:
            name: configmap-rocketmq-broker-slave-prod

        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        readinessProbe:
          tcpSocket:
            port: 10909
          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          tcpSocket:
            port: 10909
          initialDelaySeconds: 120
          periodSeconds: 10

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - pod-rocketmq-broker-slave-prod
              topologyKey: kubernetes.io/hostname

      dnsPolicy: ClusterFirst
      restartPolicy: Always